### ISSUE TITLE
Einladungen zum Freifunk-Stammtisch automatisieren

### ISSUE THREAD

**Issue by 24367dfa** [FreifunkMD/.github#23]
Damit die Erinnerung an den Stammtisch nicht daran hängt, ob der @penguineer gerade am richtigen Rechner ist. :)

3 (?) Tage vorher eine Erinnerung schicken. Termin ist immer der dritte Montag des Monats.
(cron für den Freitag vor dem dritten Montag des Monats: `1 0 11-17 * 5`)

**Comment by 24367dfa** [comment]
es gibt sogar schon eine github action :)
https://github.com/cstuder/apprise-ga

**Comment by penguineer** [comment]
> @penguineer kannst du mir einen technischen Login für unseren Mailserver organisieren, so dass ich die Mails an die Mailingliste einliefern kann?

Ja, den haben wir sowieso schon für andere Dienste. Bekommst Du per Discord.
