### ISSUE TITLE
Texte der automatischen Erinnerung mit Datum des nächsten Treffens

### ISSUE THREAD

**Issue by penguineer** [FreifunkMD/.github#31]
Unsere automatischen Erinnerungstexte sind sehr generisch. Schöner wäre es, dort das Datum zu haben (siehe https://github.com/FreifunkMD/.github/pull/28#issuecomment-1515951274).

**Comment by 24367dfa** [comment]
`date -d "next Monday"` sollte, wenn der CRON zum richtigen Zeitpunkt läuft, das Datum des nächsten Montags ausgeben.

**Comment by penguineer** [comment]
Wir brauchen also sowas wie  `date -d "next Monday" "+%d.%m."`
